name: "Pull Request Labeler"
run-name: ${{ github.actor }} is moving the data at $(date)
push:
Â Â Â  branches:
      - main      
workflow_dispatch:
     inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug    
env:
  FOLDER_NAME: src
jobs:
  move-to-folder:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Create {{ env.FOLDER_NAME }} folder if missing
Â Â Â Â Â Â Â  run: |
Â Â Â Â Â Â Â Â Â  if [ ! -d "src" ]; then
Â Â Â Â Â Â Â Â Â Â Â  mkdir {{ env.FOLDER_NAME }}
Â Â Â Â Â Â Â Â Â  fi
      - name: Move files to {{ env.FOLDER_NAME }}/
Â Â Â Â Â Â Â  run: |Â Â Â Â Â Â Â Â Â  
Â Â Â Â Â Â Â Â Â  mv *.py {{ env.FOLDER_NAME }}/
      - name: Commit and push changes
Â Â Â Â Â Â Â  run: |
Â Â Â Â Â Â Â Â Â  git config user.name "github-actions"
Â Â Â Â Â Â Â Â Â  git config user.email "github-actions@users.noreply.github.com"
Â Â Â Â Â Â Â Â Â  git add {{ env.FOLDER_NAME }}
Â Â Â Â Â Â Â Â Â  git commit -m "Move files to {{ env.FOLDER_NAME }} folder"
Â Â Â Â Â Â Â Â Â  git push

